[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.10.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
